#region 版权及版本变化申明
/*-----------------------------------------------------------------------------------------------------------
// Copyright (C) 2012 广州优亿信息科技有限公司
// 版权所有
// 
//
// 文件名：IEntityFactory.cs
// 文件功能描述：用于生成实体。
//
//
// 创建标识：宋冰（billsoff@gmail.com） 20110406
//
// 修改标识：
// 修改描述：
//
// --------------------------------------------------------------------------------------------------------*/
#endregion 版权及版本变化申明

using System;
using System.Collections.Generic;
using System.Text;



namespace Useease.GeneralDataAccess
{
	/// <summary>
	/// 用于生成实体。
	/// </summary>
	public interface IEntityFactory
	{

		/// <summary>
		/// 为实体附加对数据库会话的引用，实现是设置为 EntityManager 实例。
		/// </summary>
		/// <param name="entity">实体。</param>
		void AttachDatabaseSession(Object entity);

		/// <summary>
		/// 为业务实体附加数据库会话对象。
		/// </summary>
		/// <param name="businessObject">业务实体。</param>
		void AttachDatabaseSession(EtyBusinessObject businessObject);

		/// <summary>
		/// 为实体集合中的每个实体附加数据库会话对象。
		/// </summary>
		/// <param name="entities">实体集合。</param>
		void AttachDatabaseSession(IList<Object> entities);

		/// <summary>
		/// 为业务实体集合中的每个实体附加数据库会话对象。
		/// </summary>
		/// <param name="entities">业务实体集合。</param>
		void AttachDatabaseSession(IList<EtyBusinessObject> entities);

		/// <summary>
		/// 创建游离实体。
		/// </summary>
		/// <typeparam name="TEntity">实体类型。</typeparam>
		/// <returns>创建好的游离实体。</returns>
		TEntity CreateNew<TEntity>() where TEntity : EtyBusinessObject, new();

		/// <summary>
		/// 为实体设置候选键的值。
		/// </summary>
		/// <param name="entity">实体。</param>
		void SetAutoGeneratedCandidateKeyValue(Object entity);

		/// <summary>
		/// 为实体集合设置候选键的值，所有的实体必须为同一类型。
		/// </summary>
		/// <param name="entities">实体集合。</param>
		void SetAutoGeneratedCandidateKeyValues(IList<Object> entities);

		/// <summary>
		/// 加载原生主键的值。
		/// </summary>
		/// <param name="entity">实体。</param>
		void LoadNativePrimaryKeyValue(Object entity);

		/// <summary>
		/// 加载原生主键的值，所有的实体必须为同一类型。
		/// </summary>
		/// <param name="entities"></param>
		void LoadNativePrimaryKeyValues(IList<Object> entities);
	}
}